
package sistema;

import clases.conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;
import java.sql.SQLException;
import java.sql.Statement;

public class Empleados extends javax.swing.JFrame {

    /**
     * Creates new form Empleados
     */
    public Empleados() {
        initComponents();
        user_password objusuario=new user_password();
        dbuser=objusuario.user;
        dbpassw=objusuario.password;
        System.out.println(dbuser + dbpassw);
    }

        String dbuser; //el nombre de usuario de mysql
        String dbpassw; //la contraseña de usuario de mysql
        Connection con;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDNI_E = new javax.swing.JTextField();
        txtAPELLIDOS_E = new javax.swing.JTextField();
        txtNOMBRES_E = new javax.swing.JTextField();
        txtTELEFONO_E = new javax.swing.JTextField();
        txtDIRECCION_E = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnConsultaInd = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCosultaGral = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel1.setText("Empleados");

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/homeIcon.jpg"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel2.setText("DNI");

        jLabel3.setText("Nombres");

        jLabel4.setText("Apellidos");

        jLabel5.setText("Teléfono");

        jLabel6.setText("Dirección");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnConsultaInd.setText("Consulta individual");
        btnConsultaInd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaIndActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCosultaGral.setText("Consulta general");
        btnCosultaGral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosultaGralActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombres", "Apellidos", "Teléfono", "Dirección"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNOMBRES_E, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDNI_E, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtAPELLIDOS_E, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDIRECCION_E, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtTELEFONO_E, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnConsultaInd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCosultaGral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDNI_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNOMBRES_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAPELLIDOS_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTELEFONO_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnConsultaInd))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificar)
                            .addComponent(btnCosultaGral))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiar)
                            .addComponent(btnEliminar))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDIRECCION_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnVolver)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Main frmMain=new Main();
        frmMain.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        conexion conectar=new conexion();
        String sql;
        //insertar datos en la base de datos
        //se prepara la sentencia para insertar datos
        
        sql="INSERT INTO EMPLEADO(DNI_E,NOMBRE_E,APELLIDOS_E,TELEFONO_E,DIRECCION_E)";
        sql+="VALUES(?,?,?,?,?)";
        int DNI_E=Integer.parseInt(txtDNI_E.getText());
        String NOMBRE_E=txtNOMBRES_E.getText();
        String APELLIDOS_E=txtAPELLIDOS_E.getText();
        String TELEFONO_E=txtTELEFONO_E.getText();
        String DIRECCION_E=txtDIRECCION_E.getText();
        
            //codigo para la base de datos
        try{
                
                // se establece la conexiòn
              
                con=conectar.getConexion(dbuser, dbpassw);
                
                PreparedStatement pstm;
                pstm =(PreparedStatement)con.prepareStatement(sql);
                pstm.setInt(1,DNI_E);
                pstm.setString(2,NOMBRE_E);
                pstm.setString(3,APELLIDOS_E);
                pstm.setString(4,TELEFONO_E);
                pstm.setString(5,DIRECCION_E);
                int rtdo=pstm.executeUpdate();
                if(rtdo==1)JOptionPane.showMessageDialog(this, "Registro almacenado correctamente");
                else throw new RuntimeException("no se almaceno el registro");
                
                 con.close();
        
        }catch(RuntimeException| SQLException e){
         JOptionPane.showMessageDialog(this, "Conexion fallida");
         throw new RuntimeException(e);
                 
                 
            }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        String sql;
        conexion conectar=new conexion();

        int DNI_E=Integer.parseInt(txtDNI_E.getText());
        String NOMBRE_E=txtNOMBRES_E.getText();
        String APELLIDOS_E=txtAPELLIDOS_E.getText();
        String TELEFONO_E=txtTELEFONO_E.getText();
        String DIRECCION_E=txtDIRECCION_E.getText();
        //Proceso

        sql="UPDATE EMPLEADO SET DNI_E="+DNI_E+", NOMBRE_E='"+NOMBRE_E+"',APELLIDOS_E='"+APELLIDOS_E
             +"', TELEFONO_E='"+TELEFONO_E+"' WHERE DNI_E="+DNI_E;
             
        
        System.out.println(sql);
            //codigo para la base de datos
        try{
                
                con=conectar.getConexion(dbuser, dbpassw);
                PreparedStatement pstm;
                pstm =(PreparedStatement)con.prepareStatement(sql);
                int rtdo=pstm.executeUpdate();
                if(rtdo==1)JOptionPane.showMessageDialog(this, "Registro MODIFICADO correctamente");
                else throw new RuntimeException("no se MODIFICO el registro");
                
                con.close();
                
                }catch(RuntimeException| SQLException e){
                 e.printStackTrace();
                 JOptionPane.showMessageDialog(this, "Conexion fallida");
                 throw new RuntimeException(e);
            }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        conexion conectar=new conexion();
  
        try {
            con=conectar.getConexion(dbuser, dbpassw);

             int id=Integer.parseInt(JOptionPane.showInputDialog
              (this,"Ingrese el DNI del EMPLEADO a ELIMINAR "));
             
            Statement statement = con.createStatement();
            String sql=("DELETE FROM EMPLEADO WHERE DNI_E="+id);
            PreparedStatement pstm;
            pstm =(PreparedStatement)con.prepareStatement(sql);
            int rtdo=pstm.executeUpdate();
            if(rtdo==1)JOptionPane.showMessageDialog(this, "Registro ELIMINADO correctamente");
            else throw new RuntimeException("no se ELIMINO el registro");
             
            statement.close();
            con.close();

        }   catch(RuntimeException| SQLException e){
                 e.printStackTrace();
                 JOptionPane.showMessageDialog(this, "Conexion fallida");
                 throw new RuntimeException(e);
            }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnConsultaIndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaIndActionPerformed
        String sql;
        conexion conectar=new conexion();
        int DNI_E;
        
        try {
            con=conectar.getConexion(dbuser, dbpassw);

            DNI_E=Integer.parseInt(JOptionPane.showInputDialog
              (this,"Ingrese el DNI del empleado a consultar "));

            Statement statement = con.createStatement();
            sql=("SELECT * FROM EMPLEADO WHERE DNI_E="+DNI_E);
            ResultSet rs = statement.executeQuery(sql);
              //System.out.println("hola" + rs);
            int i=0;
            while (rs.next()) {   
                int DNI = rs.getInt("DNI_E");
                Tabla.setValueAt(DNI, i, 0);
                txtDNI_E.setText(DNI+"");
                String NOMBRE_E= rs.getString("NOMBRE_E");
                Tabla.setValueAt(NOMBRE_E, i, 1);
                txtNOMBRES_E.setText(NOMBRE_E);
                String APELLIDOS_E= rs.getString("APELLIDOS_E");
                Tabla.setValueAt(APELLIDOS_E, i, 2);
                txtAPELLIDOS_E.setText(APELLIDOS_E);
                String TELEFONO_E= rs.getString("TELEFONO_E");
                Tabla.setValueAt(TELEFONO_E, i, 3);
                txtTELEFONO_E.setText(TELEFONO_E);
                String DIRECCION_E= rs.getString("DIRECCION_E");
                Tabla.setValueAt(DIRECCION_E, i, 4);
                txtDIRECCION_E.setText(DIRECCION_E);
                ++i;
                
            }

            rs.close();
            statement.close();
            con.close();

        }     catch(RuntimeException| SQLException e){
                 e.printStackTrace();
                 JOptionPane.showMessageDialog(this, "Conexion fallida");
                 throw new RuntimeException(e);
        }
    }//GEN-LAST:event_btnConsultaIndActionPerformed

    private void btnCosultaGralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosultaGralActionPerformed
        conexion conectar=new conexion();

        try {
            con=conectar.getConexion(dbuser, dbpassw);

            Statement statement = con.createStatement();
            ResultSet rs = statement.executeQuery("SELECT * FROM EMPLEADO");
            
            int i=0;
            while (rs.next()) {
                int DNI_E = rs.getInt("DNI_E");
                Tabla.setValueAt(DNI_E, i, 0);
                
                String NOMBRE_E = rs.getString("NOMBRE_E");
                Tabla.setValueAt(NOMBRE_E, i, 1);
                
                String APELLIDOS_E= rs.getString("APELLIDOS_E");
                Tabla.setValueAt(APELLIDOS_E, i, 2);
                
                String TELEFONO_E= rs.getString("TELEFONO_E");
                Tabla.setValueAt(TELEFONO_E, i, 3);
                
                String DIRECCION_E= rs.getString("DIRECCION_E");
                Tabla.setValueAt(DIRECCION_E, i, 4);
                
                ++i;
                
            }

            rs.close();
            statement.close();
            con.close();

            }     catch(RuntimeException| SQLException e){
                 e.printStackTrace();
                 JOptionPane.showMessageDialog(this, "Conexion fallida");
                 throw new RuntimeException(e);
            }
    }//GEN-LAST:event_btnCosultaGralActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtDNI_E.setText("");
        txtNOMBRES_E.setText("");
        txtAPELLIDOS_E.setText("");
        txtTELEFONO_E.setText("");
        txtDIRECCION_E.setText("");
        txtDNI_E.requestFocus();   
         for(int i=0;i<=49;i++){
            for(int j=0;j<5;j++){
                Tabla.setValueAt("", i, j);
             }
         }
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnConsultaInd;
    private javax.swing.JButton btnCosultaGral;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAPELLIDOS_E;
    private javax.swing.JTextField txtDIRECCION_E;
    private javax.swing.JTextField txtDNI_E;
    private javax.swing.JTextField txtNOMBRES_E;
    private javax.swing.JTextField txtTELEFONO_E;
    // End of variables declaration//GEN-END:variables
}
