
package sistema;
import clases.conexion;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Pedido_Producto extends javax.swing.JFrame {

    /**
     * Creates new form Pedido_Producto
     */
    public Pedido_Producto() {
        initComponents();
        user_password objusuario=new user_password();
        dbuser=objusuario.user;
        dbpassw=objusuario.password;
        System.out.println(dbuser + dbpassw);
    }

        String dbuser; //el nombre de usuario de mysql
        String dbpassw; //la contraseña de usuario de mysql
        Connection con;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNO_VENTA = new javax.swing.JTextField();
        txtSUBTOTAL = new javax.swing.JTextField();
        txtDNI_PR = new javax.swing.JTextField();
        txtCANTIDAD = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnConsultaIndividual = new javax.swing.JButton();
        btnConsultaGeneral = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel1.setText("Pedido_Producto");

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/homeIcon.jpg"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel2.setText("Cantidad");

        jLabel3.setText("Subtotal");

        jLabel4.setText("Número Venta");

        jLabel5.setText("DNI_Poducto");

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Número venta", "Subtotal", "Cantidad", "DNI_Producto"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnConsultaIndividual.setText("Consulta individual");
        btnConsultaIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaIndividualActionPerformed(evt);
            }
        });

        btnConsultaGeneral.setText("Consulta general");
        btnConsultaGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaGeneralActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNO_VENTA, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDNI_PR, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCANTIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSUBTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnConsultaIndividual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConsultaGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNO_VENTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnGuardar)
                    .addComponent(btnConsultaIndividual))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSUBTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar)
                    .addComponent(btnConsultaGeneral))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCANTIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtDNI_PR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Main frmMain=new Main();
        frmMain.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        conexion conectar=new conexion();
        String sql;
        //insertar datos en la base de datos
        //se prepara la sentencia para insertar datos
        
        sql="INSERT INTO PEDIDO_PRODUCTO(CANTIDAD,SUBTOTAL,NO_VENTA,DNI_PR)";
        sql+="VALUES(?,?,?,?)";
        int CANTIDAD=Integer.parseInt(txtCANTIDAD.getText());
        int SUBTOTAL=Integer.parseInt(txtSUBTOTAL.getText());
        int NO_VENTA=Integer.parseInt(txtNO_VENTA.getText());
        int DNI_PR=Integer.parseInt(txtDNI_PR.getText());        
        
            //codigo para la base de datos
        try{
                
                // se establece la conexiòn
              
                con=conectar.getConexion(dbuser, dbpassw);
                
                PreparedStatement pstm;
                pstm =(PreparedStatement)con.prepareStatement(sql);
                pstm.setInt(1,CANTIDAD);
                pstm.setInt(2,SUBTOTAL);
                pstm.setInt(3,NO_VENTA);
                pstm.setInt(4,DNI_PR);
                
                int rtdo=pstm.executeUpdate();
                if(rtdo==1)JOptionPane.showMessageDialog(this, "Registro almacenado correctamente");
                else throw new RuntimeException("no se almaceno el registro");
                
                 con.close();
        
        }catch(RuntimeException| SQLException e){
         JOptionPane.showMessageDialog(this, "Conexion fallida");
         throw new RuntimeException(e);
                 
                 
            } 
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
       String sql;
        conexion conectar=new conexion();

        int CANTIDAD=Integer.parseInt(txtCANTIDAD.getText());
        int SUBTOTAL=Integer.parseInt(txtSUBTOTAL.getText());       
        int NO_VENTA=Integer.parseInt(txtNO_VENTA.getText());
        int DNI_PR=Integer.parseInt(txtDNI_PR.getText());       
        //Proceso

        sql="UPDATE PEDIDO_PRODUCTO SET CANTIDAD="+CANTIDAD+", SUBTOTAL="+SUBTOTAL+",NO_VENTA='"+NO_VENTA
             +", DNI_PR="+DNI_PR+" WHERE NO_VENTA="+NO_VENTA;
             
        
        System.out.println(sql);
            //codigo para la base de datos
        try{
                
                con=conectar.getConexion(dbuser, dbpassw);
                PreparedStatement pstm;
                pstm =(PreparedStatement)con.prepareStatement(sql);
                int rtdo=pstm.executeUpdate();
                if(rtdo==1)JOptionPane.showMessageDialog(this, "Registro MODIFICADO correctamente");
                else throw new RuntimeException("no se MODIFICO el registro");
                
                con.close();
                
                }catch(RuntimeException| SQLException e){
                 e.printStackTrace();
                 JOptionPane.showMessageDialog(this, "Conexion fallida");
                 throw new RuntimeException(e);
            }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        conexion conectar=new conexion();
  
        try {
            con=conectar.getConexion(dbuser, dbpassw);

             int id=Integer.parseInt(JOptionPane.showInputDialog
              (this,"Ingrese el DNI del pedido a ELIMINAR "));
             
            Statement statement = con.createStatement();
            String sql=("DELETE FROM PEDIDO_PRODUCTO WHERE NO_VENTA="+id);
            PreparedStatement pstm;
            pstm =(PreparedStatement)con.prepareStatement(sql);
            int rtdo=pstm.executeUpdate();
            if(rtdo==1)JOptionPane.showMessageDialog(this, "Registro ELIMINADO correctamente");
            else throw new RuntimeException("no se ELIMINO el registro");
             
            statement.close();
            con.close();

        }   catch(RuntimeException| SQLException e){
                 e.printStackTrace();
                 JOptionPane.showMessageDialog(this, "Conexion fallida");
                 throw new RuntimeException(e);
            }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnConsultaIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaIndividualActionPerformed
        String sql;
        conexion conectar=new conexion();
        int NO_VENTA;
        
        try {
            con=conectar.getConexion(dbuser, dbpassw);

            NO_VENTA=Integer.parseInt(JOptionPane.showInputDialog
              (this,"Ingrese el número de venta a consultar "));

            Statement statement = con.createStatement();
            sql=("SELECT * FROM PEDIDO_PRODUCTO WHERE NO_VENTA="+NO_VENTA);
            ResultSet rs = statement.executeQuery(sql);
              //System.out.println("hola" + rs);
            int i=0;
            while (rs.next()) {   
                int NO_VENTa = rs.getInt("NO_VENTA");
                Tabla.setValueAt(NO_VENTa, i, 0);
                txtNO_VENTA.setText(NO_VENTa+"");
                int SUBTOTAL = rs.getInt("SUBTOTAL");
                Tabla.setValueAt(SUBTOTAL, i, 1);
                txtSUBTOTAL.setText(SUBTOTAL+"");
                int CANTIDAD = rs.getInt("CANTIDAD");
                Tabla.setValueAt(CANTIDAD, i, 2);
                txtCANTIDAD.setText(CANTIDAD+"");
                int DNI = rs.getInt("DNI_PR");
                Tabla.setValueAt(DNI, i, 3);
                txtDNI_PR.setText(DNI+"");
                ++i;
                
            }

            rs.close();
            statement.close();
            con.close();

        }     catch(RuntimeException| SQLException e){
                 e.printStackTrace();
                 JOptionPane.showMessageDialog(this, "Conexion fallida");
                 throw new RuntimeException(e);
        }
    }//GEN-LAST:event_btnConsultaIndividualActionPerformed

    private void btnConsultaGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaGeneralActionPerformed
        conexion conectar=new conexion();

        try {
            con=conectar.getConexion(dbuser, dbpassw);

            Statement statement = con.createStatement();
            ResultSet rs = statement.executeQuery("SELECT * FROM PEDIDO_PRODUCTO");
            
            int i=0;
            while (rs.next()) {
                int DNI_E = rs.getInt("NO_VENTA");
                Tabla.setValueAt(DNI_E, i, 0);
                
                String NOMBRE_E = rs.getString("SUBTOTAL");
                Tabla.setValueAt(NOMBRE_E, i, 1);
                
                String APELLIDOS_E= rs.getString("CANTIDAD");
                Tabla.setValueAt(APELLIDOS_E, i, 2);
                
                String TELEFONO_E= rs.getString("DNI_PR");
                Tabla.setValueAt(TELEFONO_E, i, 3);
                
                ++i;
                
            }

            rs.close();
            statement.close();
            con.close();

            }     catch(RuntimeException| SQLException e){
                 e.printStackTrace();
                 JOptionPane.showMessageDialog(this, "Conexion fallida");
                 throw new RuntimeException(e);
            }
    }//GEN-LAST:event_btnConsultaGeneralActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtNO_VENTA.setText("");
        txtSUBTOTAL.setText("");
        txtCANTIDAD.setText("");
        txtDNI_PR.setText("");
        txtNO_VENTA.requestFocus();   
         for(int i=0;i<=49;i++){
            for(int j=0;j<4;j++){
                Tabla.setValueAt("", i, j);
             }
         }
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedido_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedido_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedido_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedido_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedido_Producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnConsultaGeneral;
    private javax.swing.JButton btnConsultaIndividual;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCANTIDAD;
    private javax.swing.JTextField txtDNI_PR;
    private javax.swing.JTextField txtNO_VENTA;
    private javax.swing.JTextField txtSUBTOTAL;
    // End of variables declaration//GEN-END:variables
}
