
package sistema;

import clases.conexion;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Pedidos extends javax.swing.JFrame {

    /**
     * Creates new form Pedidos
     */
    public Pedidos() {
        initComponents();
        user_password objusuario=new user_password();
        dbuser=objusuario.user;
        dbpassw=objusuario.password;
        System.out.println(dbuser + dbpassw);
    }
    
        String dbuser; //el nombre de usuario de mysql
        String dbpassw; //la contraseña de usuario de mysql
        Connection con;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtNumVenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFechaEntrega = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDNI_C = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDNI_E = new javax.swing.JTextField();
        txtFechaSolicitud = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        txtConsultaIndividual = new javax.swing.JButton();
        btnConsultaGeneral = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel1.setText("PEDIDOS");

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/homeIcon.jpg"))); // NOI18N
        btnVolver.setText("volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nº Venta", "Total", "FechaEntrega", "FechaSolicitud", "DNI_C", "DNI_E", "DNI_S"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jLabel2.setText("Nº Venta");

        txtNumVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumVentaActionPerformed(evt);
            }
        });

        jLabel3.setText("Total");

        jLabel4.setText("Fecha de Entrega");

        jLabel6.setText("DNI_C");

        jLabel7.setText("DNI_E");

        jLabel5.setText("Fecha de Solicitud");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.setMaximumSize(new java.awt.Dimension(2, 32));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        txtConsultaIndividual.setText("Consulta Individual");
        txtConsultaIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultaIndividualActionPerformed(evt);
            }
        });

        btnConsultaGeneral.setText("Consulta General");
        btnConsultaGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaGeneralActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNumVenta, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDNI_C)
                                .addComponent(txtFechaSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDNI_E, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConsultaIndividual)
                            .addComponent(btnConsultaGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNumVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFechaSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(btnGuardar)
                                    .addComponent(btnConsultaGeneral))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtConsultaIndividual))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtDNI_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtDNI_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnEliminar)
                                            .addComponent(btnLimpiar))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver)
                        .addGap(30, 30, 30))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Main frmMain=new Main();
        frmMain.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       conexion conectar=new conexion();
        String sql;
        //insertar datos en la base de datos
        //se prepara la sentencia para insertar datos
        
        sql="INSERT INTO pedido(NO_VENTA,TOTAL,FECHA_ENTREGA,FECHA_SOLICITUD,DNI_C,DNI_E)";
        sql+="VALUES(?,?,?,?,?,?)";
        int NO_VENTA=Integer.parseInt(txtNumVenta.getText());
        String TOTAL=txtTotal.getText();
        String FECHA_ENTREGA=txtFechaEntrega.getText();
        String FECHA_SOLICITUD=txtFechaSolicitud.getText();
        int DNI_C=Integer.parseInt(txtDNI_C.getText());
        int DNI_E=Integer.parseInt(txtDNI_E.getText());
            //codigo para la base de datos
        try{
                
                // se establece la conexiòn
              
                con=conectar.getConexion(dbuser, dbpassw);
                
                PreparedStatement pstm;
                pstm =(PreparedStatement)con.prepareStatement(sql);
                pstm.setInt(1,NO_VENTA);
                pstm.setString(2,TOTAL);
                pstm.setString(3,FECHA_ENTREGA);
                pstm.setString(4,FECHA_SOLICITUD);
                pstm.setInt(5,DNI_C);
                pstm.setInt(6,DNI_E);
                int rtdo=pstm.executeUpdate();
                if(rtdo==1)JOptionPane.showMessageDialog(this, "Registro almacenado correctamente");
                else throw new RuntimeException("no se almaceno el registro");
                
                 con.close();
        
        }catch(RuntimeException| SQLException e){
         JOptionPane.showMessageDialog(this, "Conexion fallida");
         throw new RuntimeException(e);
                 
                 
            }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtNumVenta.setText("");
        txtTotal.setText("");
        txtFechaEntrega.setText("");
        txtFechaSolicitud.setText("");
        txtDNI_C.setText("");
        txtDNI_E.setText("");
        txtNumVenta.requestFocus();   
         for(int i=0;i<=49;i++){
            for(int j=0;j<6;j++){
                tabla.setValueAt("", i, j);
             }
         }
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtConsultaIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultaIndividualActionPerformed
        String sql;
        conexion conectar=new conexion();
        int NumVenta;
        
        try {
            con=conectar.getConexion(dbuser, dbpassw);

            NumVenta=Integer.parseInt(JOptionPane.showInputDialog
              (this,"Ingrese el Nº_Venta a consultar "));

            Statement statement = con.createStatement();
            sql=("SELECT * FROM PEDIDO WHERE NO_VENTA="+NumVenta);
            ResultSet rs = statement.executeQuery(sql);
              //System.out.println("hola" + rs);
            int i=0;
            while (rs.next()) {   
                int NV = rs.getInt("NO_VENTA");
                tabla.setValueAt(NV, i, 0);
                txtNumVenta.setText(NV+"");
                int Total = rs.getInt("TOTAL");
                tabla.setValueAt(Total, i, 1);
                txtTotal.setText(Total+"");
                String Fecha_E= rs.getString("FECHA_ENTREGA");
                tabla.setValueAt(Fecha_E, i, 2);
                txtFechaEntrega.setText(Fecha_E);
                String Fecha_S= rs.getString("FECHA_SOLICITUD");
                tabla.setValueAt(Fecha_S, i, 3);
                txtFechaSolicitud.setText(Fecha_S);
                int DNI_C = rs.getInt("DNI_C");
                tabla.setValueAt(DNI_C, i, 4);
                txtDNI_C.setText(DNI_C+"");
                int DNI_E = rs.getInt("DNI_E");
                tabla.setValueAt(DNI_E, i, 5);
                txtDNI_E.setText(DNI_E+"");
                ++i;
                
            }

            rs.close();
            statement.close();
            con.close();

        }     catch(RuntimeException| SQLException e){
                 e.printStackTrace();
                 JOptionPane.showMessageDialog(this, "Conexion fallida");
                 throw new RuntimeException(e);
        }
    }//GEN-LAST:event_txtConsultaIndividualActionPerformed

    private void btnConsultaGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaGeneralActionPerformed
        conexion conectar=new conexion();

        try {
            con=conectar.getConexion(dbuser, dbpassw);

            Statement statement = con.createStatement();
            ResultSet rs = statement.executeQuery("SELECT * FROM PEDIDO");
            
            int i=0;
            while (rs.next()) {
                int NV = rs.getInt("NO_VENTA");
                tabla.setValueAt(NV, i, 0);
                
                int Total = rs.getInt("TOTAL");
                tabla.setValueAt(Total, i, 1);
                
                String Fecha_E= rs.getString("FECHA_ENTREGA");
                tabla.setValueAt(Fecha_E, i, 2);
                
                String Fecha_S= rs.getString("FECHA_SOLICITUD");
                tabla.setValueAt(Fecha_S, i, 3);
                
                int DNI_C = rs.getInt("DNI_C");
                tabla.setValueAt(DNI_C, i, 4);
               
                int DNI_E = rs.getInt("DNI_E");
                tabla.setValueAt(DNI_E, i, 5);
                
                ++i;
                
            }

            rs.close();
            statement.close();
            con.close();

            }     catch(RuntimeException| SQLException e){
                 e.printStackTrace();
                 JOptionPane.showMessageDialog(this, "Conexion fallida");
                 throw new RuntimeException(e);
            }
    }//GEN-LAST:event_btnConsultaGeneralActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        String sql;
        conexion conectar=new conexion();

        int NV=Integer.parseInt(txtNumVenta.getText());
        int Total=Integer.parseInt(txtTotal.getText());
        String Fecha_E=txtFechaEntrega.getText();
        String Fecha_S=txtFechaSolicitud.getText();
        int DNI_C=Integer.parseInt(txtDNI_C.getText());
        int DNI_E=Integer.parseInt(txtDNI_E.getText());
        //Proceso

        sql="UPDATE PEDIDO SET NO_VENTA="+NV+", TOTAL="+Total+",FECHA_ENTREGA='"+Fecha_E
             +"', FECHA_SOLICITUD='"+Fecha_S+"', DNI_C="+DNI_C+", DNI_E="+DNI_E
             +" WHERE NO_VENTA="+NV;
        
        System.out.println(sql);
            //codigo para la base de datos
        try{
                
                con=conectar.getConexion(dbuser, dbpassw);
                PreparedStatement pstm;
                pstm =(PreparedStatement)con.prepareStatement(sql);
                int rtdo=pstm.executeUpdate();
                if(rtdo==1)JOptionPane.showMessageDialog(this, "Registro MODIFICADO correctamente");
                else throw new RuntimeException("no se MODIFICO el registro");
                
                con.close();
                
                }catch(RuntimeException| SQLException e){
                 e.printStackTrace();
                 JOptionPane.showMessageDialog(this, "Conexion fallida");
                 throw new RuntimeException(e);
            }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtNumVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumVentaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
         conexion conectar=new conexion();
  
        try {
            con=conectar.getConexion(dbuser, dbpassw);

             int id=Integer.parseInt(JOptionPane.showInputDialog
              (this,"Ingrese el número de venta del pedido a ELIMINAR "));
             
            Statement statement = con.createStatement();
            String sql=("DELETE FROM PEDIDO WHERE NO_VENTA="+id);
            PreparedStatement pstm;
            pstm =(PreparedStatement)con.prepareStatement(sql);
            int rtdo=pstm.executeUpdate();
            if(rtdo==1)JOptionPane.showMessageDialog(this, "Registro ELIMINADO correctamente");
            else throw new RuntimeException("no se ELIMINO el registro");
             
            statement.close();
            con.close();

        }   catch(RuntimeException| SQLException e){
                 e.printStackTrace();
                 JOptionPane.showMessageDialog(this, "Conexion fallida");
                 throw new RuntimeException(e);
            } 
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultaGeneral;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JButton txtConsultaIndividual;
    private javax.swing.JTextField txtDNI_C;
    private javax.swing.JTextField txtDNI_E;
    private javax.swing.JTextField txtFechaEntrega;
    private javax.swing.JTextField txtFechaSolicitud;
    private javax.swing.JTextField txtNumVenta;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
